src/CultureExplorer/Models/DateTimeFormatViewModels/IndexModel.cs
using System.Collections.Generic;
using System.Globalization;

namespace CultureExplorer.Models.DateTimeFormatViewModels;

public record class IndexViewModel(
	IEnumerable<CultureInfo> CultureInfos,
	IDictionary<CultureInfo, DateTimeFormatInfo> FormatInfos);

src/CultureExplorer/Models/NumberFormatViewModels/IndexModel.cs
using System.Collections.Generic;
using System.Globalization;

namespace CultureExplorer.Models.NumberFormatViewModels;

public record class IndexViewModel(
	IEnumerable<CultureInfo> CultureInfos,
	IDictionary<CultureInfo, NumberFormatInfo> FormatInfos);

src/CultureExplorer/Models/SharedViewModels/ErrorViewModel.cs
namespace CultureExplorer.Models.SharedViewModels;

public class ErrorViewModel
{
	public string? RequestId { get; set; }

	public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/CultureExplorer/Models/TextViewModels/IndexModel.cs
using System.Collections.Generic;
using System.Globalization;

namespace CultureExplorer.Models.TextViewModels;

public record class IndexViewModel(
	IEnumerable<CultureInfo> CultureInfos,
	IDictionary<CultureInfo, TextInfo> FormatInfos);

src/CultureExplorer/Controllers/DateTimeFormatController.cs
using System.Globalization;
using System.Linq;
using CultureExplorer.Models.DateTimeFormatViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CultureExplorer.Controllers;

public class DateTimeFormatController : Controller
{
	private static readonly string[] _cultureNames = ["", "en-US", "en-UK", "de-DE", "fr-FR", "es-ES", "it-IT", "ru-RU", "jp-JP"];


	public IActionResult Index()
	{
		var cultureInfos = _cultureNames.Select(name => CultureInfo.GetCultureInfo(name)).ToList();

		var formatInfos = cultureInfos.ToDictionary(x => x, x => x.DateTimeFormat);

		IndexViewModel viewModel = new IndexViewModel(cultureInfos, formatInfos);

		return View(viewModel);
	}
}

src/CultureExplorer/Controllers/HomeController.cs
using System.Diagnostics;
using CultureExplorer.Models.SharedViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CultureExplorer.Controllers;

public class HomeController : Controller
{
	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Privacy()
	{
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

src/CultureExplorer/Controllers/NumberFormatController.cs
using System.Globalization;
using System.Linq;
using CultureExplorer.Models.NumberFormatViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CultureExplorer.Controllers;

public class NumberFormatController : Controller
{
	private static readonly string[] _cultureNames = ["", "en-US", "en-UK", "de-DE", "fr-FR", "es-ES", "it-IT", "ru-RU", "jp-JP"];


	public IActionResult Index()
	{
		var cultureInfos = _cultureNames.Select(name => CultureInfo.GetCultureInfo(name)).ToList();

		var formatInfos = cultureInfos.ToDictionary(x => x, x => x.NumberFormat);

		IndexViewModel viewModel = new IndexViewModel(cultureInfos, formatInfos);

		return View(viewModel);
	}
}

src/CultureExplorer/Controllers/TextController.cs
using System.Globalization;
using System.Linq;
using CultureExplorer.Models.TextViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CultureExplorer.Controllers;

public class TextController : Controller
{
	private static readonly string[] _cultureNames = ["", "en-US", "en-UK", "de-DE", "fr-FR", "es-ES", "it-IT", "ru-RU", "jp-JP"];


	public IActionResult Index()
	{
		var cultureInfos = _cultureNames.Select(name => CultureInfo.GetCultureInfo(name)).ToList();

		var formatInfos = cultureInfos.ToDictionary(x => x, x => x.TextInfo);

		IndexViewModel viewModel = new IndexViewModel(cultureInfos, formatInfos);

		return View(viewModel);
	}
}

src/CultureExplorer/Views/DateTimeFormat/Index.cshtml
@using System.Globalization
@using CultureExplorer.Models.DateTimeFormatViewModels
@model IndexViewModel
@{
	ViewData["Title"] = "Index";
}
<h2>DateTimeFormatInfo</h2>

<ul class="nav nav-tabs">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		string className = null;
		string id = "invariant";
		string name = "Invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active";
		}
		else
		{
			name = cultureInfo.Name;
			id = name.Replace("-", "_");
		}
		<li role="presentation" class="@className"><a href="#@id" data-toggle="tab">@name</a></li>
	}
</ul>
<div class="tab-content">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		DateTimeFormatInfo dtfi = Model.FormatInfos[cultureInfo];
		string className = "";
		string id = "invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active in";
		}
		else
		{
			id = cultureInfo.Name.Replace("-", "_");
		}
		<div class="tab-pane fade @className" id="@id">
			<table class="table table-responsive">
				<tbody>
					<tr>
						<th>Calendar (week rule)</th>
						<td>@*@dtfi.Calendar -- *@@dtfi.NativeCalendarName (@dtfi.CalendarWeekRule)</td>
					</tr>
					<tr>
						<th>AM/PM Designators</th>
						<td>
							@if (!string.IsNullOrEmpty(dtfi.AMDesignator) && !string.IsNullOrEmpty(dtfi.PMDesignator))
							{
								@:@dtfi.AMDesignator &nbsp; @dtfi.PMDesignator
							}
							else
							{
								@:(n/a)
							}
						</td>
					</tr>
					<tr>
						<th>Date/Time Separators</th>
						<td>
							@if (!string.IsNullOrEmpty(dtfi.DateSeparator) && !string.IsNullOrEmpty(dtfi.TimeSeparator))
							{
								@:@dtfi.DateSeparator &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; @dtfi.TimeSeparator
							}
						</td>
					</tr>
					<tr>
						<th>FirstDayOfWeek</th>
						<td>@dtfi.FirstDayOfWeek</td>
					</tr>
					<tr>
						<th>FullDateTimePattern</th>
						<td>@dtfi.FullDateTimePattern</td>
					</tr>
					<tr>
						<th>UniversalSortableDateTimePattern</th>
						<td>@dtfi.UniversalSortableDateTimePattern</td>
					</tr>
					<tr>
						<th>SortableDateTimePattern</th>
						<td>@dtfi.SortableDateTimePattern</td>
					</tr>
					<tr>
						<th>RFC1123Pattern</th>
						<td>@dtfi.RFC1123Pattern</td>
					</tr>
					<tr>
						<th>LongDatePattern</th>
						<td>@dtfi.LongDatePattern</td>
					</tr>
					<tr>
						<th>ShortDatePattern</th>
						<td>@dtfi.ShortDatePattern</td>
					</tr>
					<tr>
						<th>YearMonthPattern</th>
						<td>@dtfi.YearMonthPattern</td>
					</tr>
					<tr>
						<th>MonthDayPattern</th>
						<td>@dtfi.MonthDayPattern</td>
					</tr>
					<tr>
						<th>LongTimePattern</th>
						<td>@dtfi.LongTimePattern</td>
					</tr>
					<tr>
						<th>ShortTimePattern</th>
						<td>@dtfi.ShortTimePattern</td>
					</tr>
					<tr>
						<th>MonthNames</th>
						<td>@string.Join(", ", dtfi.MonthNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>MonthGenitiveNames</th>
						<td>@string.Join(", ", dtfi.MonthGenitiveNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>AbbreviatedMonthNames</th>
						<td>@string.Join(", ", dtfi.AbbreviatedMonthNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>AbbreviatedMonthGenitiveNames</th>
						<td>@string.Join(", ", dtfi.AbbreviatedMonthGenitiveNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>DayNames</th>
						<td>@string.Join(", ", dtfi.DayNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>ShortestDayNames</th>
						<td>@string.Join(", ", dtfi.ShortestDayNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
					<tr>
						<th>AbbreviatedDayNames</th>
						<td>@string.Join(", ", dtfi.AbbreviatedDayNames.Where(x => !string.IsNullOrEmpty(x)))</td>
					</tr>
				</tbody>
			</table>
		</div>
	}
</div>

src/CultureExplorer/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-md-3">
		<h2>Date/Time Format</h2>
		<ul>
			<li>View <a asp-controller="DateTimeFormat" asp-action="Index">Date/Time Format</a>.</li>
		</ul>
	</div>
	<div class="col-sm-12 col-md-4">
		<h2>Number Format</h2>
		<ul>
			<li>View <a asp-controller="NumberFormat" asp-action="Index">Number Format</a>.</li>
		</ul>
	</div>
	<div class="col-sm-12 col-md-4">
		<h2>Text</h2>
		<ul>
			<li>View <a asp-controller="Text" asp-action="Index">Text</a>.</li>
		</ul>
	</div>
</div>

src/CultureExplorer/Views/NumberFormat/Index.cshtml
@using System.Globalization
@using CultureExplorer.Models.NumberFormatViewModels
@model IndexViewModel
@{
	ViewData["Title"] = "Index";
}
<h2>NumberFormatInfo</h2>

<ul class="nav nav-tabs">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		string className = null;
		string id = "invariant";
		string name = "Invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active";
		}
		else
		{
			name = cultureInfo.Name;
			id = name.Replace("-", "_");
		}
		<li role="presentation" class="@className"><a href="#@id" data-toggle="tab">@name</a></li>
	}
</ul>
<div class="tab-content">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		NumberFormatInfo nfi = Model.FormatInfos[cultureInfo];
		string className = "";
		string id = "invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active in";
		}
		else
		{
			id = cultureInfo.Name.Replace("-", "_");
		}
		<div class="tab-pane fade @className" id="@id">
			<table class="table table-responsive">
				<tbody>
					<tr>
						<th>NaNSymbol</th>
						<td>@nfi.NaNSymbol</td>
						<th>PositiveInfinitySymbol</th>
						<td>@nfi.PositiveInfinitySymbol</td>
						<th>NegativeInfinitySymbol</th>
						<td>@nfi.NegativeInfinitySymbol</td>
					</tr>
					<tr>
						<th>PerMilleSymbol</th>
						<td>@nfi.PerMilleSymbol</td>
						<th>CurrencySymbol</th>
						<td>@nfi.CurrencySymbol</td>
						<th>PercentSymbol</th>
						<td>@nfi.PercentSymbol</td>
					</tr>
					<tr>
						<th>NumberDecimalDigits</th>
						<td>@nfi.NumberDecimalDigits</td>
						<th>CurrencyDecimalDigits</th>
						<td>@nfi.CurrencyDecimalDigits</td>
						<th>PercentDecimalDigits</th>
						<td>@nfi.PercentDecimalDigits</td>
					</tr>
					<tr>
						<th>NumberDecimalSeparator</th>
						<td>@nfi.NumberDecimalSeparator</td>
						<th>CurrencyDecimalSeparator</th>
						<td>@nfi.CurrencyDecimalSeparator</td>
						<th>PercentDecimalSeparator</th>
						<td>@nfi.PercentDecimalSeparator</td>
					</tr>
					<tr>
						<th>NumberGroupSizes</th>
						<td>@string.Join(", ", nfi.NumberGroupSizes.Select(x => x.ToString()))</td>
						<th>CurrencyGroupSizes</th>
						<td>@string.Join(", ", nfi.CurrencyGroupSizes.Select(x => x.ToString()))</td>
						<th>PercentGroupSizes</th>
						<td>@string.Join(", ", nfi.PercentGroupSizes.Select(x => x.ToString()))</td>
					</tr>
					<tr>
						<th>NumberGroupSeparator</th>
						<td>@nfi.NumberGroupSeparator</td>
						<th>CurrencyGroupSeparator</th>
						<td>@nfi.CurrencyGroupSeparator</td>
						<th>PercentGroupSeparator</th>
						<td>@nfi.PercentGroupSeparator</td>
					</tr>
					<tr>
						<th>NumberNegativePattern</th>
						<td>@nfi.NumberNegativePattern</td>
						<th>CurrencyNegativePattern</th>
						<td>@nfi.CurrencyNegativePattern</td>
						<th>PercentNegativePattern</th>
						<td>@nfi.PercentNegativePattern</td>
					</tr>
					<tr>
						<th>NativeDigits</th>
						<td>@string.Join(", ", nfi.NativeDigits.Select(x => x.ToString()))</td>
						<th>CurrencyPositivePattern</th>
						<td>@nfi.CurrencyPositivePattern</td>
						<th>PercentPositivePattern</th>
						<td>@nfi.PercentPositivePattern</td>
					</tr>
					<tr>
						<th>PositiveSign</th>
						<td>@nfi.PositiveSign</td>
						<th>NegativeSign</th>
						<td>@nfi.NegativeSign</td>
						<th>DigitSubstitution</th>
						<td>@nfi.DigitSubstitution</td>
					</tr>
				</tbody>
			</table>
		</div>
	}
</div>

src/CultureExplorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Culture Explorer</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<header>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Culture Explorer</a>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
						<li><a asp-area="" asp-controller="DateTimeFormat" asp-action="Index">Date/Time</a></li>
						<li><a asp-area="" asp-controller="NumberFormat" asp-action="Index">Number</a></li>
						<li><a asp-area="" asp-controller="Text" asp-action="Index">Text</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<partial name="_CookieConsentPartial" />

	<main class="container body-content" role="main">
		@RenderBody()
	</main>

	<footer class="footer">
		<div class="container">
			<span class="text-muted">&copy; 2018 Benn Benson</span>
		</div>
	</footer>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
			asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
			asp-fallback-test="window.jQuery"
			crossorigin="anonymous"
			integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
			asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
			asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
			crossorigin="anonymous"
			integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>

src/CultureExplorer/Views/Text/Index.cshtml
@using System.Globalization
@using CultureExplorer.Models.TextViewModels
@model IndexViewModel
@{
	ViewData["Title"] = "Index";
}
<h2>TextInfo</h2>

<ul class="nav nav-tabs">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		string className = null;
		string id = "invariant";
		string name = "Invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active";
		}
		else
		{
			name = cultureInfo.Name;
			id = name.Replace("-", "_");
		}
		<li role="presentation" class="@className"><a href="#@id" data-toggle="tab">@name</a></li>
	}
</ul>
<div class="tab-content">
	@foreach (var cultureInfo in Model.CultureInfos)
	{
		TextInfo ti = Model.FormatInfos[cultureInfo];
		string className = "";
		string id = "invariant";
		if (string.IsNullOrEmpty(cultureInfo.Name))
		{
			className = "active in";
		}
		else
		{
			id = cultureInfo.Name.Replace("-", "_");
		}
		<div class="tab-pane fade @className" id="@id">
			<table class="table table-responsive">
				<tbody>
					<tr>
						<th>Culture Name</th>
						<td>@ti.CultureName</td>
						<th>ANSI Code Page</th>
						<td>@ti.ANSICodePage</td>
					</tr>
					<tr>
						<th>LCID</th>
						<td>@ti.LCID (@($"{ti.LCID:X4}"))</td>
						<th>EBCDIC Code Page</th>
						<td>@ti.EBCDICCodePage</td>
					</tr>
					<tr>
						<th>RTL?</th>
						<td>@(ti.IsRightToLeft ? "Yes" : "No")</td>
						<th>Mac Code Page</th>
						<td>@ti.MacCodePage</td>
					</tr>
					<tr>
						<th>List Separator</th>
						<td>@ti.ListSeparator</td>
						<th>OEM Code PAge</th>
						<td>@ti.OEMCodePage</td>
					</tr>
				</tbody>
			</table>
		</div>
	}
</div>